- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: validate-toml
#   - id: no-go-testing
#   - id: gometalinter
#   - id: golangci-lint
#   - id: go-critic
- repo: https://github.com/pre-commit/pre-commit-hooks
  sha: v1.4.0
  hooks:
    - id: check-yaml
      exclude: ^deployments/helm/honeydipper/
    - id: check-json
    - id: detect-private-key
