---
defaults: &defaults
  docker:
    - image: golang:1.11.1-alpine3.8
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
  working_directory: /go/src/github.com/honeyscience/honeydipper

version: 2
jobs:
  lint:
    <<: *defaults
    steps:
      - run:
          name: addinggit
          command: apk add git
      - run:
          name: addinggolint
          command: go get -u golang.org/x/lint/golint
      - checkout
      - run:
          name: gofmt
          command: go fmt
      - run:
          name: golint
          command: golint
  test:
    <<: *defaults
    steps:
      - run:
          name: addingosdeps
          command: apk add git gcc libc-dev
      - run:
          name: addingdep
          command: go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run:
          name: dependencies
          command: dep ensure
      - run:
          name: govet
          command: go vet
      - run:
          name: gotest
          command: go test -v ./...
  integration:
    <<: *defaults
    steps:
      - run:
          name: addingosdeps
          command: apk add git gcc libc-dev redis
      - run:
          name: addingdep
          command: go get -u github.com/golang/dep/cmd/dep
      - checkout
      - run:
          name: dependencies
          command: dep ensure
      - run:
          name: redis
          command: redis-server --bind 127.0.0.1
          background: true
      - run:
          name: build
          command: go install ./...
      - run:
          name: gointegrationtest
          command: go test -tags=integration -v ./...
  build:
    <<: *defaults
    deploy:
      docker:
        image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: dockerbuildpush
          command: |
            export VERSION=$(git describe --exact-match --tags $(git log -n1 --pretty='%h'))
            export TAG=us.gcr.io/$GOOGLE_PROJECT_ID/honeydipper:$VERSION
            docker build -t $TAG .
            echo $GCLOUD_CIRCLE_CI_ACCOUNT | base64 --decode | sudo gcloud auth activate-service-account --key-file=-
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud docker -- push $TAG

workflows:
  version: 2
  run_tests:
    jobs:
      - lint:
          filters:
            tags:
              ignore: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: /.*/
      - test:
          requires:
            - lint
          filters:
            tags:
              ignore: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: /.*/
      - integration:
          requires:
            - test
          filters:
            tags:
              ignore: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: /.*/
  build:
    jobs:
      - lint:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - test:
          requires:
            - lint
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - integration:
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
      - build:
          requires:
            - integration
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
