apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "honeydipper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "honeydipper.name" . }}
    helm.sh/chart: {{ include "honeydipper.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.daemon.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "honeydipper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "honeydipper.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.daemon.spec }}
{{ toYaml . | indent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.daemon.useSource }}
          image: "golang:alpine"
          command:
            - "/bin/sh"
            - "-c"
            - |
              apk add openssh git &&
              go get -u github.com/golang/dep/cmd/dep &&
              mkdir -p ~/.ssh &&
              chmod 700 ~/.ssh &&
              echo $'Host github.com\n\tStrictHostKeyChecking\tno\n\tUserKnownHostsFile\t/dev/null\n\tIdentityFile\t'{{ .Values.daemon.gitIdentityFilePath }}/id_rsa > ~/.ssh/config &&
              mkdir -p /go/src/github.com/honeyscience &&
              cd /go/src/github.com/honeyscience &&
              git clone git@github.com:honeyscience/honeydipper.git &&
              cd honeydipper &&
              git checkout {{ .Values.daemon.useBranch }} &&
              dep ensure &&
              go install ./... &&
              honeydipper {{ range $k, $v := .Values.daemon.args }}{{ quote $v }}{{ end }} ||
              sleep 3600
          {{- else }}
          image: "{{ .Values.daemon.image.repository }}:{{ .Values.daemon.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.daemon.image.pullPolicy }}
    {{- with .Values.daemon.args }}
          args:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.daemon.env }}
          env:
{{ toYaml . | indent 12 }}
    {{- end }}
    {{- with .Values.daemon.volumeMounts }}
          volumeMounts:
{{ toYaml . | indent 12 }}
    {{- end }}
          resources:
{{ toYaml .Values.daemon.resources | indent 12 }}
    {{- with .Values.daemon.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.daemon.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.daemon.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.daemon.volumes }}
      volumes:
{{ toYaml . | indent 8 }}
    {{- end }}
